name: Build PySide6 Application

on:
  push:

jobs: 
  build-windows-x64:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.11 x64
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
          architecture: x64

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install virtualenv
          virtualenv venv
          .\\venv\\Scripts\\activate
          pip install -r requirements.txt
          pip install nuitka zstandard

      - name: Build application for Windows x64
        run: |
          mkdir deploy
          Get-ChildItem -Path . -Exclude deploy,venv | Move-Item -Destination deploy
          cd deploy
          ..\venv\Scripts\activate
          nuitka  --follow-imports mesh_receiver.py
          
      - name: Archive Windows x64 build
        uses: actions/upload-artifact@v2
        with:
          name: pyside6-application-windows-x64
          path: deploy/mesh_receiver.exe
